---
- name: Test ansible facts with Morpheus run.
  hosts: all
  gather_facts: yes
  tasks:
    - debug: 
        msg: The inteface name is {{ ansible_default_ipv4.interface }}

    - debug:
        msg: This is the value of typeahead {{ morpheus['customOptions']['fmultiple'] }}