---
- hosts: all !unassigned
  become: yes
  become_method: sudo
  gather_facts: yes

  tasks:
    - yum: "name={{ item }} state=present"
      with_items:
        - git
        - wget
        - curl
        - vim
