---
- name: This sets up a service by accepting values from Option Types.
  hosts: all
  become: yes
  become_user: root
  become_method: sudo
  tasks:
  - name: Install package
    yum:
      name: "{{ morpheus['customOptions']['fpackagename'] }}"
      state: present
  - name: ensure "{{ morpheus['customOptions']['fpackagename'] }}" is running
    service:
      name: "{{ morpheus['customOptions']['fpackagename'] }}" 
      state: started
  - name: Open port for "{{ morpheus['customOptions']['fpackagename'] }}" access
    firewalld:
      service: "{{ morpheus['customOptions']['fpackagename'] }}"
      permanent: true
      state: enabled
  - name: Restart the firewalld service to load in the firewall changes
    service: 
      name: firewalld 
      state: restarted