---
- name: Custom report based on Instance Summary report
  hosts: all
  gather_facts: yes
  become: yes
  become_user: root
  become_method: sudo
  tasks:
  - name: Select query to test_db with named_args
    mysql_query:
      login_db: morpheus
      login_host: 10.30.20.164
      login_user: morpheus
      login_password: 
      #query: SELECT id, name FROM instance WHERE name like %(instance_name)s
      query: select name, date_created, cores_per_socket, status, plan_id, max_cores, provision_zone_id, max_memory, max_storage, created_by_id from instance
      #named_args:
       # instance_name: aa
  