---
- name: dump all
  hosts: all
 
  tasks:
    - name: Print some debug information 
      vars:  
        #msg: |
        #  Module Variables ("vars"):
        #  --------------------------------
        #  {{ vars | to_nice_json }} 
        #  
        #  Environment Variables ("environment"):
        #  --------------------------------
        #  {{ environment | to_nice_json }} 
        #  
        #  GROUP NAMES Variables ("group_names"):
        #  --------------------------------
        #  {{ group_names | to_nice_json }}
        #  
        #  GROUPS Variables ("groups"):
        #  --------------------------------
        #  {{ groups | to_nice_json }}
        #  
        #  HOST Variables ("hostvars"):
         # --------------------------------
        #  {{ hostvars | to_nice_json }} 
        gmsg: |
          GROUPS Variables ("groups"):
          --------------------------------
          {{ hostvars[inventory_hostname]['env'] }}

          Just var:
          --------------------------------------
          {{ env }}
    
      debug: 
        msg: "{{ gmsg.split('\n') }}"       
      tags: debug_info