---
- name: dump all
  hosts: development
 
  tasks:
    - name: Print some debug information 
      vars:  
        gmsg: |
          GROUPS Variables ("groups"):
          --------------------------------
          {{ groups | to_nice_json }}
    
      debug: 
        msg: "{{ gmsg.split('\n') }}"       
      tags: debug_info