---
- name: This is to add user on instances
  hosts: localhost

  collections:
  - f5networks.f5_module

  tasks:
  - name: Create pool
    bigip_pool:
      state: present
      name: anishtest
      partition: Common
      lb_method: least-connections-member
      slow_ramp_time: 120
      provider:
        server: 10.30.32.31
        user: admin
        password: admin
        validate_certs: no
        server_port: 8443
    delegate_to: localhost
    