---
- name: This is to add user on instances
  hosts: all
  tasks:
  - name: Create pool
    bigip_pool:
      state: present
      name: anishtest
      partition: Common
      lb_method: least-connections-member
      slow_ramp_time: 120
      provider:
        server: 10.30.32.31
        user: admin
        password: admin
        validate_certs: no
    delegate_to: localhost
    