---
- hosts: all
  gather_facts: true
  tasks:
    - debug:
        #morpheus: "{{ morpheus }}"
        #msg: "{{ morpheus['morpheus']}}"
        #msg: "{{ morpheus['accountNumber'] }}"
        msg: "{{ morpheus['instance']['container']['server']['internalIp'] }}"
        msg: "{{ morpheus['instance']['container']['server']['osType'] }}"
    
    - debug:
        msg: "{{ morpheus['user']['account'] }}"
      delegate_to: localhost