---
- hosts: localhost
  gather_facts: true
  tasks:
    - debug:
        #morpheus: "{{ morpheus }}"
        #msg: "{{ morpheus['morpheus']}}"
        #msg: "{{ morpheus['accountNumber'] }}"
        msg: "{{ morpheus['account']['accountNumber'] }}"
      