---
- name: Read contents of a file
  hosts: all
  become: yes
  become_user: root
  become_method: sudo
  tasks:
  - name: slurp file
    slurp:
      src: /home/ips
    register: remote_file
  
  - name: Read
    debug: 
      msg: "{{ remote_file['content'].split('\n') | b64decode }}"
      