---
- name: Refresh clouds.
  hosts: all
  gather_facts: yes
  become: yes
  become_user: root
  become_method: sudo
  tasks:
  - name: Refresh the clouds
    uri:
      url: https://demo.morpheusdata.com/api/zones/{{ items }}
      HEADER_Content-Type: "application/json"
      HEADER_Authorization: "Bearer 8178b6a2-1f0a-4942-8c99-e3b8a99f004a"
      method: PUT
      body: "{{ lookup('file','update_cloud.json') }}"
      body_format: json
      with_items:
        - 1
        - 44