---
- name: Refresh clouds.
  hosts: all
  gather_facts: yes
  become: yes
  become_user: root
  become_method: sudo
  tasks:
  - name: Refresh the clouds
    uri:
      url: https://dcra-vm-cmpdev-1.ren.pt/api/zones/{{ item }}
      HEADER_Content-Type: "application/json"
      HEADER_Authorization: "Bearer ce9400e5-c145-4b16-a583-8a743f57d192"
      method: PUT
      body: "{{ lookup('file','update_cloud.json') }}"
      body_format: json
    with_items:
        - 2
        - 32