---
- name: Update DB to reserve the next unused VLAN
  hosts: all
  gather_facts: yes
  become: yes
  become_user: root
  become_method: sudo
  tasks:
  
  - name: Get the next available VLAN
    shell: /bin/mysql -h 10.30.20.173 -umorpheus -p"{{ lookup('cypher','secret=secret/renmysqlpass') }}" -B -e "use vlan_capture; select vlan from vlan_capture where status like 'unused' limit 1;"
    register: free_vlan
  
  - set_fact:
      free_vlan={{ free_vlan.stdout[5:] }}
  - debug: var=free_vlan
    run_once: true


