---
- name: This will pause the tasks for 20 minutes and then complete
  hosts: all
  gather_facts: yes
  become: yes
  become_user: root
  become_method: sudo
  tasks:
  - name: the final countdown of 1200 seconds
    debug:
      msg: "{{item}} seconds to detonation"
    with_sequence: start=1200 end=0 stride=-1
