---
- name: This will pause the tasks for 20 minutes and then complete
  hosts: all
  gather_facts: yes
  become: yes
  become_user: root
  become_method: sudo
  tasks:
  - name:  Pause for 20minutes
    pause:
      minutes: 20
