---
- hosts: all
  gather_facts: true
  tasks:
    - debug:
        msg: "{{ morpheus['instance']['Id'] }}"
        msg: "{{ item }}"
      loop: 
        - "{{ hostvars[inventory_hostname]['morpheus']['morpheus']['apiAccessToken'] | to_nice_yaml }}"

  tasks:
    - debug:
        msg: "{{ item }}"
      loop: 
        - "{{ hostvars[inventory_hostname]['morpheus'] | to_nice_yaml }}"
      
        